version: '3'
services:

  fhir-listener-service:
    image: ${FHIR_LISTENER_DOCKER_SERVICE_NAME}
    build:
      context: ${PROJECT_PATH}/fhir-listener-service
      dockerfile: ${PROJECT_PATH}/fhir-listener-service/Dockerfile
    ports:
      - "${FHIR_LISTENER_PORT}:${FHIR_LISTENER_PORT}"
    restart: always
    depends_on:
      - postgres
    environment:
      - PROJECT_PATH=${PROJECT_PATH}
      - DRIVER_CLASS_NAME=${DRIVER_CLASS_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - FHIR_LOG_FILENAME=${FHIR_LOG_FILENAME}
      - FHIR_LOG_FILENAME_PATTERN=${FHIR_LOG_FILENAME_PATTERN}
      - FHIR_LOG_CONSOLE_PATTERN=${FHIR_LOG_CONSOLE_PATTERN}
      - FHIR_LOG_FILE_PATTERN=${FHIR_LOG_FILE_PATTERN}
      - FHIR_LOG_MAX_HISTORY=${FHIR_LOG_MAX_HISTORY}
      - FHIR_LOG_TOTAL_SIZE_CAP=${FHIR_LOG_TOTAL_SIZE_CAP}
      - FHIR_PROTOCOL=${FHIR_PROTOCOL}
      - FHIR_LISTENER_PORT=${FHIR_LISTENER_PORT}
      - FHIR_LISTENER_DOCKER_SERVICE_NAME=${FHIR_LISTENER_DOCKER_SERVICE_NAME}
      - FHIR_LISTENER_APPLICATION_NAME=${FHIR_LISTENER_APPLICATION_NAME}
      - FHIR_LISTENER_CONTEXT_PATH=${FHIR_LISTENER_CONTEXT_PATH}
      - FHIR_LISTENER_SERVICE_BASE_URL=${FHIR_LISTENER_SERVICE_BASE_URL}
      - FHIR_ADAPTER_PORT=${FHIR_ADAPTER_PORT}
      - FHIR_ADAPTER_DOCKER_SERVICE_NAME=${FHIR_ADAPTER_DOCKER_SERVICE_NAME}
      - FHIR_ADAPTER_APPLICATION_NAME=${FHIR_ADAPTER_APPLICATION_NAME}
      - FHIR_ADAPTER_CONTEXT_PATH=${FHIR_ADAPTER_CONTEXT_PATH}
      - FHIR_ADAPTER_SERVICE_BASE_URL=${FHIR_ADAPTER_SERVICE_BASE_URL}
      - FHIR_USER_PORT=${FHIR_USER_PORT}
      - FHIR_USER_DOCKER_SERVICE_NAME=${FHIR_USER_DOCKER_SERVICE_NAME}
      - FHIR_USER_APPLICATION_NAME=${FHIR_USER_APPLICATION_NAME}
      - FHIR_USER_CONTEXT_PATH=${FHIR_USER_CONTEXT_PATH}
      - FHIR_USER_SERVICE_BASE_URL=${FHIR_PROTOCOL}://${FHIR_USER_DOCKER_SERVICE_NAME}:${FHIR_USER_PORT}
      - FHIR_AUTH_PORT=${FHIR_AUTH_PORT}
      - FHIR_AUTH_DOCKER_SERVICE_NAME=${FHIR_AUTH_DOCKER_SERVICE_NAME}
      - FHIR_AUTH_APPLICATION_NAME=${FHIR_AUTH_APPLICATION_NAME}
      - FHIR_AUTH_CONTEXT_PATH=${FHIR_AUTH_CONTEXT_PATH}
      - FHIR_AUTH_SERVICE_BASE_URL=${FHIR_PROTOCOL}://${FHIR_AUTH_DOCKER_SERVICE_NAME}:${FHIR_AUTH_PORT}
      - FHIR_PUBLIC_KEY_FILE_NAME=fhir_public_key.der
      - FHIR_PRIVATE_KEY_FILE_NAME=fhir_private_key.der
      - HAPI_FHIR_SERVER_BASE_URL=${HAPI_FHIR_SERVER_BASE_URL}
      - FHIR_ACCESS_KEY_ID=${FHIR_ACCESS_KEY_ID}
      - FHIR_SECRET_ACCESS_KEY=${FHIR_SECRET_ACCESS_KEY}
      - CLIENT_REGISTRY_ENABLED_COUNTRY=${CLIENT_REGISTRY_ENABLED_COUNTRY}
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_MANAGEMENT_PORT=${RABBITMQ_MANAGEMENT_PORT}
      - RABBITMQ_AMQP_PORT=${RABBITMQ_AMQP_PORT}
      - RABBITMQ_USER_NAME=${RABBITMQ_USER_NAME}
      - RABBITMQ_USER_PASSWORD=${RABBITMQ_USER_PASSWORD}
      - RABBITMQ_QUEUE_NAME=${RABBITMQ_QUEUE_NAME}
      - RABBITMQ_EXCHANGE_NAME=${RABBITMQ_EXCHANGE_NAME}
      - RABBITMQ_ROUTING_KEY=${RABBITMQ_ROUTING_KEY}
    volumes:
      - ${PROJECT_PATH}/log:/log
    networks:
      - fhir-app-db-network

  fhir-adapter-service:
    image: ${FHIR_ADAPTER_DOCKER_SERVICE_NAME}
    build:
      context: ${PROJECT_PATH}/fhir-adapter-service
      dockerfile: ${PROJECT_PATH}/fhir-adapter-service/Dockerfile
    ports:
      - "${FHIR_ADAPTER_PORT}:${FHIR_ADAPTER_PORT}"
    restart: always
    depends_on:
      - postgres
    environment:
      - PROJECT_PATH=${PROJECT_PATH}
      - DRIVER_CLASS_NAME=${DRIVER_CLASS_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - FHIR_LOG_FILENAME=${FHIR_LOG_FILENAME}
      - FHIR_LOG_FILENAME_PATTERN=${FHIR_LOG_FILENAME_PATTERN}
      - FHIR_LOG_CONSOLE_PATTERN=${FHIR_LOG_CONSOLE_PATTERN}
      - FHIR_LOG_FILE_PATTERN=${FHIR_LOG_FILE_PATTERN}
      - FHIR_LOG_MAX_HISTORY=${FHIR_LOG_MAX_HISTORY}
      - FHIR_LOG_TOTAL_SIZE_CAP=${FHIR_LOG_TOTAL_SIZE_CAP}
      - FHIR_PROTOCOL=${FHIR_PROTOCOL}
      - FHIR_LISTENER_PORT=${FHIR_LISTENER_PORT}
      - FHIR_LISTENER_DOCKER_SERVICE_NAME=${FHIR_LISTENER_DOCKER_SERVICE_NAME}
      - FHIR_LISTENER_APPLICATION_NAME=${FHIR_LISTENER_APPLICATION_NAME}
      - FHIR_LISTENER_CONTEXT_PATH=${FHIR_LISTENER_CONTEXT_PATH}
      - FHIR_LISTENER_SERVICE_BASE_URL=${FHIR_LISTENER_SERVICE_BASE_URL}
      - FHIR_ADAPTER_PORT=${FHIR_ADAPTER_PORT}
      - FHIR_ADAPTER_DOCKER_SERVICE_NAME=${FHIR_ADAPTER_DOCKER_SERVICE_NAME}
      - FHIR_ADAPTER_APPLICATION_NAME=${FHIR_ADAPTER_APPLICATION_NAME}
      - FHIR_ADAPTER_CONTEXT_PATH=${FHIR_ADAPTER_CONTEXT_PATH}
      - FHIR_ADAPTER_SERVICE_BASE_URL=${FHIR_ADAPTER_SERVICE_BASE_URL}
      - FHIR_USER_PORT=${FHIR_USER_PORT}
      - FHIR_USER_DOCKER_SERVICE_NAME=${FHIR_USER_DOCKER_SERVICE_NAME}
      - FHIR_USER_APPLICATION_NAME=${FHIR_USER_APPLICATION_NAME}
      - FHIR_USER_CONTEXT_PATH=${FHIR_USER_CONTEXT_PATH}
      - FHIR_USER_SERVICE_BASE_URL=${FHIR_PROTOCOL}://${FHIR_USER_DOCKER_SERVICE_NAME}:${FHIR_USER_PORT}
      - FHIR_AUTH_PORT=${FHIR_AUTH_PORT}
      - FHIR_AUTH_DOCKER_SERVICE_NAME=${FHIR_AUTH_DOCKER_SERVICE_NAME}
      - FHIR_AUTH_APPLICATION_NAME=${FHIR_AUTH_APPLICATION_NAME}
      - FHIR_AUTH_CONTEXT_PATH=${FHIR_AUTH_CONTEXT_PATH}
      - FHIR_AUTH_SERVICE_BASE_URL=${FHIR_PROTOCOL}://${FHIR_AUTH_DOCKER_SERVICE_NAME}:${FHIR_AUTH_PORT}
      - FHIR_PUBLIC_KEY_FILE_NAME=fhir_public_key.der
      - FHIR_PRIVATE_KEY_FILE_NAME=fhir_private_key.der
      - HAPI_FHIR_SERVER_BASE_URL=${HAPI_FHIR_SERVER_BASE_URL}
      - FHIR_ACCESS_KEY_ID=${FHIR_ACCESS_KEY_ID}
      - FHIR_SECRET_ACCESS_KEY=${FHIR_SECRET_ACCESS_KEY}
      - CLIENT_REGISTRY_ENABLED_COUNTRY=${CLIENT_REGISTRY_ENABLED_COUNTRY}
      - SOURCE_DATABASE_URL=${SOURCE_DATABASE_URL}
      - SOURCE_DATABASE_USERNAME=${SOURCE_DATABASE_USERNAME}
      - SOURCE_DATABASE_PASSWORD=${SOURCE_DATABASE_PASSWORD}
      - SOURCE_DRIVER_CLASS_NAME=${SOURCE_DRIVER_CLASS_NAME}
    volumes:
      - ${PROJECT_PATH}/log:/log
    networks:
      - fhir-app-db-network

  fhir-user-service:
    image: ${FHIR_USER_DOCKER_SERVICE_NAME}
    build:
      context: ${PROJECT_PATH}/fhir-user-service
      dockerfile: ${PROJECT_PATH}/fhir-user-service/Dockerfile
    ports:
      - "${FHIR_USER_PORT}:${FHIR_USER_PORT}"
    restart: always
    depends_on:
      - postgres
    environment:
      - PROJECT_PATH=${PROJECT_PATH}
      - DRIVER_CLASS_NAME=${DRIVER_CLASS_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - FHIR_LOG_FILENAME=${FHIR_LOG_FILENAME}
      - FHIR_LOG_FILENAME_PATTERN=${FHIR_LOG_FILENAME_PATTERN}
      - FHIR_LOG_CONSOLE_PATTERN=${FHIR_LOG_CONSOLE_PATTERN}
      - FHIR_LOG_FILE_PATTERN=${FHIR_LOG_FILE_PATTERN}
      - FHIR_LOG_MAX_HISTORY=${FHIR_LOG_MAX_HISTORY}
      - FHIR_LOG_TOTAL_SIZE_CAP=${FHIR_LOG_TOTAL_SIZE_CAP}
      - FHIR_PROTOCOL=${FHIR_PROTOCOL}
      - FHIR_LISTENER_PORT=${FHIR_LISTENER_PORT}
      - FHIR_LISTENER_DOCKER_SERVICE_NAME=${FHIR_LISTENER_DOCKER_SERVICE_NAME}
      - FHIR_LISTENER_APPLICATION_NAME=${FHIR_LISTENER_APPLICATION_NAME}
      - FHIR_LISTENER_CONTEXT_PATH=${FHIR_LISTENER_CONTEXT_PATH}
      - FHIR_LISTENER_SERVICE_BASE_URL=${FHIR_LISTENER_SERVICE_BASE_URL}
      - FHIR_ADAPTER_PORT=${FHIR_ADAPTER_PORT}
      - FHIR_ADAPTER_DOCKER_SERVICE_NAME=${FHIR_ADAPTER_DOCKER_SERVICE_NAME}
      - FHIR_ADAPTER_APPLICATION_NAME=${FHIR_ADAPTER_APPLICATION_NAME}
      - FHIR_ADAPTER_CONTEXT_PATH=${FHIR_ADAPTER_CONTEXT_PATH}
      - FHIR_ADAPTER_SERVICE_BASE_URL=${FHIR_ADAPTER_SERVICE_BASE_URL}
      - FHIR_USER_PORT=${FHIR_USER_PORT}
      - FHIR_USER_DOCKER_SERVICE_NAME=${FHIR_USER_DOCKER_SERVICE_NAME}
      - FHIR_USER_APPLICATION_NAME=${FHIR_USER_APPLICATION_NAME}
      - FHIR_USER_CONTEXT_PATH=${FHIR_USER_CONTEXT_PATH}
      - FHIR_USER_SERVICE_BASE_URL=${FHIR_PROTOCOL}://${FHIR_USER_DOCKER_SERVICE_NAME}:${FHIR_USER_PORT}
      - FHIR_AUTH_PORT=${FHIR_AUTH_PORT}
      - FHIR_AUTH_DOCKER_SERVICE_NAME=${FHIR_AUTH_DOCKER_SERVICE_NAME}
      - FHIR_AUTH_APPLICATION_NAME=${FHIR_AUTH_APPLICATION_NAME}
      - FHIR_AUTH_CONTEXT_PATH=${FHIR_AUTH_CONTEXT_PATH}
      - FHIR_AUTH_SERVICE_BASE_URL=${FHIR_PROTOCOL}://${FHIR_AUTH_DOCKER_SERVICE_NAME}:${FHIR_AUTH_PORT}
      - FHIR_PUBLIC_KEY_FILE_NAME=fhir_public_key.der
      - FHIR_PRIVATE_KEY_FILE_NAME=fhir_private_key.der
      - HAPI_FHIR_SERVER_BASE_URL=${HAPI_FHIR_SERVER_BASE_URL}
      - FHIR_ACCESS_KEY_ID=${FHIR_ACCESS_KEY_ID}
      - FHIR_SECRET_ACCESS_KEY=${FHIR_SECRET_ACCESS_KEY}
      - CLIENT_REGISTRY_ENABLED_COUNTRY=${CLIENT_REGISTRY_ENABLED_COUNTRY}
    volumes:
      - ${PROJECT_PATH}/log:/log
    networks:
      - fhir-app-db-network
  fhir-auth-service:
    image: ${FHIR_AUTH_DOCKER_SERVICE_NAME}
    build:
      context: ${PROJECT_PATH}/fhir-auth-service
      dockerfile: ${PROJECT_PATH}/fhir-auth-service/Dockerfile
    ports:
      - "${FHIR_AUTH_PORT}:${FHIR_AUTH_PORT}"
    restart: always
    depends_on:
      - postgres
    environment:
      - PROJECT_PATH=${PROJECT_PATH}
      - DRIVER_CLASS_NAME=${DRIVER_CLASS_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - FHIR_LOG_FILENAME=${FHIR_LOG_FILENAME}
      - FHIR_LOG_FILENAME_PATTERN=${FHIR_LOG_FILENAME_PATTERN}
      - FHIR_LOG_CONSOLE_PATTERN=${FHIR_LOG_CONSOLE_PATTERN}
      - FHIR_LOG_FILE_PATTERN=${FHIR_LOG_FILE_PATTERN}
      - FHIR_LOG_MAX_HISTORY=${FHIR_LOG_MAX_HISTORY}
      - FHIR_LOG_TOTAL_SIZE_CAP=${FHIR_LOG_TOTAL_SIZE_CAP}
      - FHIR_PROTOCOL=${FHIR_PROTOCOL}
      - FHIR_LISTENER_PORT=${FHIR_LISTENER_PORT}
      - FHIR_LISTENER_DOCKER_SERVICE_NAME=${FHIR_LISTENER_DOCKER_SERVICE_NAME}
      - FHIR_LISTENER_APPLICATION_NAME=${FHIR_LISTENER_APPLICATION_NAME}
      - FHIR_LISTENER_CONTEXT_PATH=${FHIR_LISTENER_CONTEXT_PATH}
      - FHIR_LISTENER_SERVICE_BASE_URL=${FHIR_LISTENER_SERVICE_BASE_URL}
      - FHIR_ADAPTER_PORT=${FHIR_ADAPTER_PORT}
      - FHIR_ADAPTER_DOCKER_SERVICE_NAME=${FHIR_ADAPTER_DOCKER_SERVICE_NAME}
      - FHIR_ADAPTER_APPLICATION_NAME=${FHIR_ADAPTER_APPLICATION_NAME}
      - FHIR_ADAPTER_CONTEXT_PATH=${FHIR_ADAPTER_CONTEXT_PATH}
      - FHIR_ADAPTER_SERVICE_BASE_URL=${FHIR_ADAPTER_SERVICE_BASE_URL}
      - FHIR_USER_PORT=${FHIR_USER_PORT}
      - FHIR_USER_DOCKER_SERVICE_NAME=${FHIR_USER_DOCKER_SERVICE_NAME}
      - FHIR_USER_APPLICATION_NAME=${FHIR_USER_APPLICATION_NAME}
      - FHIR_USER_CONTEXT_PATH=${FHIR_USER_CONTEXT_PATH}
      - FHIR_USER_SERVICE_BASE_URL=${FHIR_PROTOCOL}://${FHIR_USER_DOCKER_SERVICE_NAME}:${FHIR_USER_PORT}
      - FHIR_AUTH_PORT=${FHIR_AUTH_PORT}
      - FHIR_AUTH_DOCKER_SERVICE_NAME=${FHIR_AUTH_DOCKER_SERVICE_NAME}
      - FHIR_AUTH_APPLICATION_NAME=${FHIR_AUTH_APPLICATION_NAME}
      - FHIR_AUTH_CONTEXT_PATH=${FHIR_AUTH_CONTEXT_PATH}
      - FHIR_AUTH_SERVICE_BASE_URL=${FHIR_PROTOCOL}://${FHIR_AUTH_DOCKER_SERVICE_NAME}:${FHIR_AUTH_PORT}
      - FHIR_PUBLIC_KEY_FILE_NAME=fhir_public_key.der
      - FHIR_PRIVATE_KEY_FILE_NAME=fhir_private_key.der
      - HAPI_FHIR_SERVER_BASE_URL=${HAPI_FHIR_SERVER_BASE_URL}
      - FHIR_ACCESS_KEY_ID=${FHIR_ACCESS_KEY_ID}
      - FHIR_SECRET_ACCESS_KEY=${FHIR_SECRET_ACCESS_KEY}
      - CLIENT_REGISTRY_ENABLED_COUNTRY=${CLIENT_REGISTRY_ENABLED_COUNTRY}
      - PASSWORD=${PASSWORD}
    volumes:
      - ${PROJECT_PATH}/log:/log
    networks:
      - fhir-app-db-network

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    networks:
      - fhir-app-db-network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_PATH}/nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - fhir-app-db-network

networks:
  fhir-app-db-network:
    driver: bridge

volumes:
  cache:
    driver: local
  postgres:
    driver: local
